### ISSUE TITLE
Nytt spørsmål & svar: jeg har data jeg vil dele

### ISSUE THREAD

**Issue by kleivane** [data-altinn-no/docs#1]
På: https://docs.data.altinn.no/ofte-stilte-spørsmål/

Hva med et punkt på "jeg har data jeg vil dele"?

Jeg fant mye informasjon på hvordan konsumere, men mindre på hvordan man kan ta i bruk data.altinn som tilbyder av data :)

**Comment by erlendoksvoll** [comment]
Det skal vi nok få til - tenker det er naturlig del av #3 :)
