### ISSUE TITLE
Registering av ny bruker feiler i testmiljø

### ISSUE THREAD

**Issue by kleivane** [data-altinn-no/docs#2]
Feilen "Invalid field 'appType' specified" kommer når jeg prøver å opprette en bruker i testmiljøet deres :) 
Og det ser ikke ut til å være et felt jeg kan fylle ut selv. 

<img width="349" alt="Screenshot 2022-10-06 at 15 24 09" src="https://user-images.githubusercontent.com/660063/194324723-6f342563-c2d9-448c-b355-0d269d9b75d7.png">

Safari på MacOS

**Comment by nlundee** [comment]
Hei!

Takk for tilbakemeldingen, dette skal være løst nå 😃
